CREATE DATABASE BLOGMASTER;
GO;

USE BLOGMASTER;
GO;

CREATE TABLE AUTHORS(
    [ID] INT NOT NULL IDENTITY(1,1),
    [NAME] VARCHAR(100) NOT NULL,
    [PASSWORD] VARCHAR(30) NOT NULL,
    [CPF] VARCHAR(11),
    [DATEOFBIRTH] DATETIME,

    CONSTRAINT PK_AUTHORS PRIMARY KEY([ID])
);
GO;

CREATE TABLE POSTS(
    [ID] INT NOT NULL IDENTITY(1,1),
    [TITLE] VARCHAR(120) NOT NULL,
    [DESCRIPTION] VARCHAR(250) NOT NULL,
    [POSTDATE] DATETIME NOT NULL,
    [AUTHORID] INT NOT NULL,

    CONSTRAINT PK_POSTS PRIMARY KEY([ID]),
    CONSTRAINT FK_POSTS_AUTHORS FOREIGN KEY ([AUTHORID]) REFERENCES AUTHORS([ID]) ON DELETE CASCADE
);
GO;

CREATE TABLE COMMENTS(
    [POSTID] INT NOT NULL,
    [AUTHORID] INT NOT NULL,
    [DESCRIPTION] VARCHAR(180) NOT NULL,
    [DATEOFPOSTING] DATETIME NOT NULL,

    CONSTRAINT PK_COMMENTS PRIMARY KEY([POSTID], [AUTHORID], [DATEOFPOSTING]),
    CONSTRAINT FK_COMMENTS_AUTHORS FOREIGN KEY([AUTHORID]) REFERENCES AUTHORS([ID]),
    CONSTRAINT FK_COMMENTS_POSTS FOREIGN KEY([POSTID]) REFERENCES POSTS([ID])
);
GO;

CREATE TABLE KEYWORDS(
    [POSTID] INT NOT NULL,
    [WORD] VARCHAR(40) NOT NULL,

    CONSTRAINT FK_KEYWORDS_POSTS FOREIGN KEY([POSTID]) REFERENCES POSTS([ID])
);